<a href="https://colab.research.google.com/github/Edwin372/BasicHandsOnML/blob/main/Pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Working with pytorch tensors

In [ ]:
import torch

print(torch.__version__)

1.11.0+cu113


Only floating point data type is support as the default type in Pytorch

In [ ]:
torch.get_default_dtype()

torch.float32

In [ ]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

##Creating and initializing tensors

In [ ]:
#Create tensor from array using torch.Tensor
torch_arr = torch.Tensor([[1,2,3], [4,5,6]])
torch_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#init int tensor
torch.IntTensor([[1,2,3],[4,5,6]])
# or 
torch.tensor([[1,2],[3,5]])

tensor([[1, 2],
        [3, 5]])

In [ ]:
#check is tensor
torch.is_tensor(torch_arr)

True

In [ ]:
# count number of element 
torch.numel(torch_arr)

6

In [ ]:
# init tensor with shape
tensor_init = torch.Tensor(2,2)
tensor_init

tensor([[5.9465e-316, 4.9407e-324],
        [4.9407e-324, 4.9407e-324]])

In [ ]:
#init tensor with shape using rand
tensor_init = torch.rand(2,3)
tensor_init

tensor([[0.3492, 0.2917, 0.6833],
        [0.1492, 0.8041, 0.6237]])

In [ ]:
# init tensor with dtype
torch.tensor([1,2]).type(torch.float32)

tensor([1., 2.], dtype=torch.float32)

In [ ]:
#create tensor with specified shape and a inital value
tensor_fill = torch.full((2,5), fill_value=10,)
tensor_fill

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [ ]:
#create tensor of ones
tensor_ones = torch.ones(2,5).type(torch.int)
tensor_ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [ ]:
#create tensor of zeros
tensor_zeros = torch.zeros(2,5)
tensor_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
#Create unit matrix
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#find none zeros positions in a matrix
none_zero = torch.nonzero(tensor_eye)
none_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
# make copy of array, list, tensor
i = torch.tensor([[0, 1,1], [2, 2, 0]])

In [ ]:
v = torch.tensor([3, 4, 5]).type(torch.float32)

In [ ]:
#construct parse tensor in coordinate format with non-zero element at indices with the given values
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [ ]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

##Simple operations

Operations that modify the tensor in-place have a "_" suffix

In [ ]:
initial_tensor = torch.rand(2, 3)

In [ ]:
initial_tensor.fill_(10)
print(initial_tensor)

tensor([[10., 10., 10.],
        [10., 10., 10.]])


In [ ]:
# not all operation have inplace version
initial_tensor.fill(10)

AttributeError: ignored

In [ ]:
t = initial_tensor.add(5)
t

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [ ]:
initial_tensor.add_(5)
print(initial_tensor)

tensor([[15., 15., 15.],
        [15., 15., 15.]])


In [ ]:
t.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [ ]:
# create tensor within a range with even space
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [ ]:
tensor_chunk = torch.chunk(x, 3, 0) # chunk into 3 part according to 0 axis
tensor1, tensor2, tensor3 =  tensor_chunk

In [ ]:
torch.cat((tensor1, tensor2, tensor3), 0) # concat 3 tensor according to 0 axis

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [ ]:
random = torch.rand(3,3)
random

tensor([[0.3906, 0.8524, 0.1274],
        [0.6597, 0.4550, 0.2174],
        [0.8182, 0.0499, 0.0195]])

In [ ]:
random[0,1]

tensor(0.8524)

In [ ]:
random.size()

torch.Size([3, 3])

In [ ]:
#view a tensor in a different shape, this does not create new tensor
random.view(9)

tensor([0.3906, 0.8524, 0.1274, 0.6597, 0.4550, 0.2174, 0.8182, 0.0499, 0.0195])

In [ ]:
resized = random.view(-1)
resized

tensor([0.3906, 0.8524, 0.1274, 0.6597, 0.4550, 0.2174, 0.8182, 0.0499, 0.0195])

In [ ]:
random[2,2] = 100
#this show that resized have its memory shared with random
resized

tensor([3.9061e-01, 8.5240e-01, 1.2744e-01, 6.5967e-01, 4.5502e-01, 2.1742e-01,
        8.1820e-01, 4.9886e-02, 1.0000e+02])

In [ ]:
# add dim to tensor
unsqueeze = torch.unsqueeze(random, 2)
print(unsqueeze)
unsqueeze.shape

tensor([[[3.9061e-01],
         [8.5240e-01],
         [1.2744e-01]],

        [[6.5967e-01],
         [4.5502e-01],
         [2.1742e-01]],

        [[8.1820e-01],
         [4.9886e-02],
         [1.0000e+02]]])


torch.Size([3, 3, 1])

##Elementwise and matrix Operations on Tensors

In [ ]:
#sort
sorted, sorted_indices = torch.sort(random)
sorted

tensor([[1.2744e-01, 3.9061e-01, 8.5240e-01],
        [2.1742e-01, 4.5502e-01, 6.5967e-01],
        [4.9886e-02, 8.1820e-01, 1.0000e+02]])

In [ ]:
sorted_indices

tensor([[2, 0, 1],
        [2, 1, 0],
        [1, 0, 2]])

In [ ]:
F = torch.linspace(start=-5, end=5, steps=5).type(torch.int)
F

tensor([-5, -2,  0,  2,  5], dtype=torch.int32)

In [ ]:
#abs
abs = torch.abs(F)
abs

tensor([5, 2, 0, 2, 5], dtype=torch.int32)

In [ ]:
#add
add = F + F
print(add)
add2 = torch.add(F, F)
print(add2)

tensor([-10,  -4,   0,   4,  10], dtype=torch.int32)
tensor([-10,  -4,   0,   4,  10], dtype=torch.int32)


In [ ]:
#dividing
div = torch.div(F, F + 0.3)
div

tensor([1.0638, 1.1765, 0.0000, 0.8696, 0.9434])

In [ ]:
#multiplying 
mul = torch.mul(F, F)
mul

tensor([25,  4,  0,  4, 25], dtype=torch.int32)

In [ ]:
#put a limit within range between 0 and 2 
clamp = torch.clamp(F, min=0, max=2)
clamp

tensor([0, 0, 0, 2, 2], dtype=torch.int32)

In [ ]:
# dot product
v1 = torch.rand(3)
v2 = torch.rand(3)
torch.dot(v1,v2)

tensor(1.0495)

In [ ]:
# matrix multiplication
m1 = torch.rand(3,3)
m2 = torch.rand(3, 2)
print(torch.matmul(m1,m2))
#or
print(torch.mm(m1,m2))

tensor([[0.4952, 0.5504],
        [0.7262, 0.3924],
        [0.5820, 0.3672]])
tensor([[0.4952, 0.5504],
        [0.7262, 0.3924],
        [0.5820, 0.3672]])


In [ ]:
# multiply a matrix and a vector
mv = torch.mv(m1, v1)
mv

tensor([0.6358, 0.7997, 0.8349])

In [ ]:
# find max/min along an axis in a matrix
print(torch.argmax(torch.matmul(m1,m2), dim=1))
print(torch.argmin(torch.matmul(m1,m2), dim=1))
print(torch.argmax(torch.matmul(m1,m2), dim=0))
print(torch.argmin(torch.matmul(m1,m2), dim=0))

tensor([1, 0, 0])
tensor([0, 1, 1])
tensor([1, 0])
tensor([0, 2])


## Convert between pytorch and numpy

In [ ]:
tensor = torch.rand(5,5)
type(tensor)

torch.Tensor

In [ ]:
np_from_tensor = tensor.numpy()
print(type(np_from_tensor))


numpy.ndarray

# Pytorch and GPU

In [ ]:
x = F.cuda()

In [ ]:
x

tensor([-5, -2,  0,  2,  5], device='cuda:0', dtype=torch.int32)

In [ ]:
x = torch.tensor([1,2], device='cuda:0')

In [ ]:
x

tensor([1, 2], device='cuda:0')

In [ ]:
print('Outsite with context: ', torch.cuda.current_device())
with torch.cuda.device(0):
  print('Inside with context: ', torch.cuda.current_device)

print('Outside with context again', torch.cuda.current_device())

Outsite with context:  0
Inside with context:  <function current_device at 0x7f54d444add0>
Outside with context again 0


In [ ]:
with torch.cuda.device(0):
  a = torch.tensor([10, 20])
  b = torch.tensor([10, 20], device=torch.cuda.current_device())


In [ ]:
a

tensor([10, 20])

In [ ]:
b

tensor([10, 20], device='cuda:0')

In [ ]:
c = a.cuda() + b
print(c)

tensor([20, 40], device='cuda:0')


In [ ]:
c

tensor([20, 40], device='cuda:0')

In [ ]:
torch.cuda.memory_allocated()

2560

In [ ]:
torch.cuda.memory_cached()

/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:386: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)


2097152

In [ ]:
torch.cuda.empty_cache()

#Working with gradient using AutoGrad

In [ ]:
import torch

